Updating data and documentation files
beanumber/comvlong pull request #2
Opened 2023-03-06 20:11 UTC by m-sezgin

2023-03-08 12:42 UTC, beanumber commented
As per our conversation Monday are you planning to make another push to this PR @m-sezgin ?

2023-03-08 15:56 UTC, m-sezgin commented
just pushed!

2023-03-08 16:44 UTC, beanumber requested changes
Let's talk about this later today.

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'   \item{time_hh}{Hour of incident.}
What do you think about converting these four variables into a timestamp? Wouldn't that be more efficient storage-wise?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'   \item{offense}{"code for an offense; seems to correspond to a section in the Massachusetts General Laws e.g. '90160' is MGL c.90 §16" (Woke Windows).}
Can we add a link to this? 

https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXIV/Chapter90/Section16

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'   \item{disposition_desc}{a character vector}
But what does it mean?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'   \item{location_name}{a character vector}
The location in which the offense occurred

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'   \item{court_code}{"see \href{https://www.mass.gov/info-details/trial-court-codes-numerical-listing}{Trial Court codes} for mapping" (Woke Windows)}
Hmm...should we add these as helper data frames?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'     \item{plate_type}{This is likely plate type as specified \href{https://www.mass.gov/doc/passenger-plates-manual/download}{here}}
Likely?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'     \item{clocked}{A character vector.}
Indicating what?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#'     \item{race}{The race of the violator. Races with an insufficient number of entries were not included in this dataset. a character vector.}
Isn't this omitted in favor of `race_clean`?

2023-03-08 16:44 UTC, beanumber commented on R/data.R
> +#' An object of class \code{tbl_df} (inherits from \code{tbl}, \code{data.frame}) with 328141 rows and 45 columns.
Are these numbers still accurate?

2023-03-08 16:44 UTC, beanumber commented on data-raw/woke_windows.R
> +  sample_n(150000)
I'm thinking now about whether a random sample is preferable to a set of years...

2023-03-08 16:44 UTC, beanumber commented on data-raw/woke_windows.R
> +  sample_n(150000)
As per the comment above, we could add something like:

`mutate(event_timestamp = lubridate::parse_date_time(...))`

2023-03-20 13:45 UTC, beanumber commented
@m-sezgin are you planning to push any commits to this before our meeting this afternoon?

2023-03-20 15:30 UTC, m-sezgin commented
I pushed but I'm running into some issues with court code documentation and datetimes

2023-04-17 04:16 UTC, m-sezgin commented
Requested changes have been made. Only issues are that `clocked` and `plate_type` documentation are still unknown.

2023-05-01 15:53 UTC, merged